spring:
  application:
    name: GATEWAY-SERVICE

  profiles:
    active: local

  cloud:
    gateway:
      routes:
        - id: api-service
          uri: lb://API-SERVICE
          predicates:
            - Path=/api/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**

server:
  port: 8765

jwt:
  secret: xircle