name: xircle server CI/CD

on:
  pull_request:
    branches: [main]

jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Login in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
  build-and-push:
    needs: docker-login
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, post-service, follow-service, gateway-service, discovery-service, config-service]
        include:
          - service: user-service
          - service: post-service
          - service: follow-service
          - service: gateway-service
          - service: discovery-service
          - service: config-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Grant execute permission for Gradle
        run: chmod +x gradlew
      - name: Build Service (${{ matrix.service }})
        run: ./gradlew :${{ matrix.service }}:bootBuildImage